### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by janat08**
You can run it on windows right?

### CODE REVIEW

**Comment by gpdm** [comment]
May need to document the actual procedure for initialializing the USB key on Windows.

**Comment by janat08** [comment]
I barely got a reasonably good error message on the docker step, after I
run it right within wsl because the commands are unix. Do you not have
windows? Maybe someone else does and can write it up in a pinch. I believe
it had something to do with output going in some temporary directory or
something which exists nowhere even wsl apparently.

**Comment by gpdm** [comment]
@janat08 
Not keen on promising too much here. I do have some Windows machine running WSL, but I would definitely need to throw a look at it as well. I don't typically do dev stuff there, but use Linux VMs for such kind of activities.

But maybe, just to rule out some things in advance, are we talking WSL or WSL2? Because to my knowledge, only the latter supports docker on Windows to some extend.
And also just to double-down, even if you installed WSL2 on your Windows machine, did you actually set WSL for the linux environment to use V2 over V1, as in ...

```
wsl --set-version <distro> 2
```

My experience so far was, even when updating WSL2, any created environment would still default to WSL V1.
But maybe that's also just because I have this borked experimentation machine, where I started off with WSL(v1) in the first place.

Also posting the error messages, however incomplete they may be, might help to got some first insights.

Best,
-GP

**Comment by gpdm** [comment]
added FAQ entry in https://github.com/gpdm/tinycore-targetdisplaymode/tree/1.1

Build verified on Windows 10, with WSL 2 and Ubuntu. Worked for me.

**Pull request closed without merging**
